# Generated by Django 5.0.6 on 2026-08-25 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('apelido', models.CharField(blank=True, max_length=60)),
                ('idade', models.PositiveSmallIntegerField(default=17)),
                ('nacionalidade', models.CharField(max_length=80)),
                ('altura', models.PositiveSmallIntegerField(default=178, help_text='Altura em centímetros.')),
                ('pe_dominante', models.CharField(choices=[('direito', 'Direito'), ('esquerdo', 'Esquerdo'), ('ambidestro', 'Ambidestro')], default='direito', max_length=12)),
                ('posicao', models.CharField(choices=[('goleiro', 'Goleiro'), ('zagueiro', 'Zagueiro'), ('lateral_esquerdo', 'Lateral Esquerdo'), ('lateral_direito', 'Lateral Direito'), ('volante', 'Volante'), ('meia', 'Meia'), ('meia_atacante', 'Meia Atacante'), ('ponta_esquerda', 'Ponta Esquerda'), ('ponta_direita', 'Ponta Direita'), ('segundo_atacante', 'Segundo Atacante'), ('atacante', 'Atacante')], max_length=20)),
                ('perfil', models.CharField(choices=[('finalizador', 'Finalizador'), ('velocista', 'Velocista'), ('criador', 'Criador'), ('driblador', 'Driblador'), ('defensor', 'Defensor'), ('completo', 'Completo')], default='completo', max_length=20)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('lesionado', 'Lesionado'), ('aposentado', 'Aposentado')], default='ativo', max_length=15)),
                ('overall', models.PositiveSmallIntegerField(default=50)),
                ('forma_atual', models.SmallIntegerField(default=0, help_text='-10 a +10, afeta desempenho nas partidas.')),
                ('condicao_fisica', models.PositiveSmallIntegerField(default=100, help_text='0-100, energia disponível para jogar/treinar.')),
                ('moral', models.PositiveSmallIntegerField(default=70, help_text='0-100.')),
                ('reputacao', models.PositiveSmallIntegerField(default=10, help_text='0-100.')),
                ('valor_mercado', models.BigIntegerField(default=100000)),
                ('salario_semanal', models.BigIntegerField(default=1000)),
                ('saldo', models.BigIntegerField(default=0, help_text='Saldo acumulado do jogador (prêmios, salários recebidos).')),
                ('convocado_selecao', models.BooleanField(default=False)),
                ('temporada_atual', models.CharField(default='2026/27', max_length=9)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('clube_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elenco', to='clubs.club')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jogador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
                'ordering': ['-overall'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidade', models.PositiveSmallIntegerField(default=50)),
                ('aceleracao', models.PositiveSmallIntegerField(default=50)),
                ('finalizacao', models.PositiveSmallIntegerField(default=50)),
                ('passe', models.PositiveSmallIntegerField(default=50)),
                ('drible', models.PositiveSmallIntegerField(default=50)),
                ('forca', models.PositiveSmallIntegerField(default=50)),
                ('defesa', models.PositiveSmallIntegerField(default=50)),
                ('fisico', models.PositiveSmallIntegerField(default=50)),
                ('inteligencia', models.PositiveSmallIntegerField(default=50)),
                ('posicionamento', models.PositiveSmallIntegerField(default=50)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('jogador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='players.player')),
            ],
            options={
                'verbose_name': 'Atributos do Jogador',
                'verbose_name_plural': 'Atributos dos Jogadores',
            },
        ),
    ]
