# Generated by Django 5.0.6 on 2026-08-25 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_semanal', models.BigIntegerField()),
                ('duracao_anos', models.PositiveSmallIntegerField()),
                ('ano_inicio', models.PositiveSmallIntegerField()),
                ('ano_fim', models.PositiveSmallIntegerField()),
                ('clausula_rescisoria', models.BigIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('assinado_em', models.DateTimeField(auto_now_add=True)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='clubs.club')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='players.player')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'ordering': ['-assinado_em'],
            },
        ),
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gravidade', models.CharField(choices=[('muscular', 'Lesão Muscular'), ('entorse', 'Entorse'), ('grave', 'Lesão Grave')], max_length=10)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('semanas_totais', models.PositiveSmallIntegerField()),
                ('semanas_restantes', models.PositiveSmallIntegerField()),
                ('penalidade_fisico_temporaria', models.SmallIntegerField(default=5, help_text='Quanto o atributo físico cai temporariamente durante a lesão.')),
                ('ocorrida_em', models.DateTimeField(auto_now_add=True)),
                ('recuperada', models.BooleanField(default=False)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesoes', to='players.player')),
            ],
            options={
                'verbose_name': 'Lesão',
                'verbose_name_plural': 'Lesões',
                'ordering': ['-ocorrida_em'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.BigIntegerField()),
                ('salario_semanal_oferecido', models.BigIntegerField()),
                ('duracao_anos', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada'), ('negociando', 'Em Negociação'), ('expirada', 'Expirada')], default='pendente', max_length=12)),
                ('rodadas_negociacao', models.PositiveSmallIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('clube_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas_recebidas', to='clubs.club')),
                ('clube_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propostas_enviadas', to='clubs.club')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='players.player')),
            ],
            options={
                'verbose_name': 'Transferência',
                'verbose_name_plural': 'Transferências',
                'ordering': ['-criada_em'],
            },
        ),
    ]
