# Generated by Django 5.0.6 on 2026-08-25 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=60, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.CharField(max_length=255)),
                ('icone', models.CharField(default='🏆', max_length=10)),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
            },
        ),
        migrations.CreateModel(
            name='DecisionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.SlugField(max_length=80, unique=True)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('contexto', models.CharField(choices=[('treino', 'Treino'), ('partida', 'Partida'), ('clube', 'Clube'), ('imprensa', 'Imprensa'), ('transferencia', 'Transferência'), ('pessoal', 'Pessoal')], default='clube', max_length=30)),
            ],
            options={
                'verbose_name': 'Evento de Decisão',
                'verbose_name_plural': 'Eventos de Decisão',
            },
        ),
        migrations.CreateModel(
            name='CareerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=9)),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('clube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='players.player')),
            ],
            options={
                'verbose_name': 'Histórico de Carreira',
                'verbose_name_plural': 'Históricos de Carreira',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='DecisionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(help_text='Ex: A, B, C', max_length=2)),
                ('texto', models.CharField(max_length=200)),
                ('efeito_moral', models.SmallIntegerField(default=0)),
                ('efeito_reputacao', models.SmallIntegerField(default=0)),
                ('efeito_relacao_treinador', models.SmallIntegerField(default=0)),
                ('efeito_relacao_torcida', models.SmallIntegerField(default=0)),
                ('efeito_valor_mercado_percentual', models.SmallIntegerField(default=0, help_text='Variação percentual no valor de mercado, ex: 5 = +5%.')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='career.decisionevent')),
            ],
            options={
                'verbose_name': 'Opção de Decisão',
                'verbose_name_plural': 'Opções de Decisão',
                'ordering': ['letra'],
            },
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decidido_em', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.decisionevent')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes_tomadas', to='players.player')),
                ('opcao_escolhida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.decisionoption')),
            ],
            options={
                'verbose_name': 'Registro de Decisão',
                'verbose_name_plural': 'Registros de Decisão',
                'ordering': ['-decidido_em'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('corpo', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('partida', 'Partida'), ('transferencia', 'Transferência'), ('selecao', 'Seleção'), ('lesao', 'Lesão'), ('premio', 'Prêmio'), ('contrato', 'Contrato'), ('geral', 'Geral')], default='geral', max_length=30)),
                ('publicada_em', models.DateTimeField(auto_now_add=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='players.player')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-publicada_em'],
            },
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('finalizacao', 'Treino de Finalização'), ('fisico', 'Treino Físico'), ('velocidade', 'Treino de Velocidade'), ('passe', 'Treino de Passe'), ('drible', 'Treino de Drible'), ('defensivo', 'Treino Defensivo')], max_length=20)),
                ('energia_consumida', models.PositiveSmallIntegerField(default=15)),
                ('ganhos', models.JSONField(default=dict, help_text="Ex: {'finalizacao': 2, 'velocidade': 1}")),
                ('realizado_em', models.DateTimeField(auto_now_add=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='players.player')),
            ],
            options={
                'verbose_name': 'Treinamento',
                'verbose_name_plural': 'Treinamentos',
                'ordering': ['-realizado_em'],
            },
        ),
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desbloqueada_em', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desbloqueios', to='career.achievement')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='players.player')),
            ],
            options={
                'verbose_name': 'Conquista do Jogador',
                'verbose_name_plural': 'Conquistas dos Jogadores',
                'ordering': ['-desbloqueada_em'],
                'unique_together': {('jogador', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(help_text='Ex: 2026/27', max_length=9)),
                ('competicao_principal', models.CharField(default='Campeonato Nacional', max_length=120)),
                ('jogos', models.PositiveSmallIntegerField(default=0)),
                ('gols', models.PositiveSmallIntegerField(default=0)),
                ('assistencias', models.PositiveSmallIntegerField(default=0)),
                ('cartoes_amarelos', models.PositiveSmallIntegerField(default=0)),
                ('cartoes_vermelhos', models.PositiveSmallIntegerField(default=0)),
                ('nota_media', models.DecimalField(decimal_places=1, default=6.0, max_digits=3)),
                ('overall_inicio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overall_fim', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('encerrada', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('clube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temporadas', to='clubs.club')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='players.player')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['-ano'],
                'unique_together': {('jogador', 'ano')},
            },
        ),
    ]
