# Generated by Django 5.0.6 on 2026-08-25 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('continental', 'Continental'), ('copa_nacional', 'Copa Nacional'), ('selecao', 'Seleção')], max_length=20)),
                ('continente', models.CharField(blank=True, max_length=40)),
                ('prestigio', models.PositiveSmallIntegerField(default=50)),
            ],
            options={
                'verbose_name': 'Competição',
                'verbose_name_plural': 'Competições',
                'ordering': ['-prestigio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('pais', models.CharField(max_length=80)),
                ('nivel', models.PositiveSmallIntegerField(default=1, help_text='1 = elite, 2 = segunda divisão, etc.')),
                ('prestigio', models.PositiveSmallIntegerField(default=50, help_text='0-100, usado para calcular reputação e propostas.')),
            ],
            options={
                'verbose_name': 'Liga',
                'verbose_name_plural': 'Ligas',
                'ordering': ['-prestigio', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('pais', models.CharField(max_length=80)),
                ('overall_minimo', models.PositiveSmallIntegerField(default=55, help_text='Overall mínimo aproximado do elenco - usado para gerar propostas coerentes.')),
                ('orcamento', models.BigIntegerField(default=10000000, help_text='Orçamento de mercado em euros.')),
                ('prestigio', models.PositiveSmallIntegerField(default=50)),
                ('escudo_cor_primaria', models.CharField(default='#1e293b', max_length=7)),
                ('escudo_cor_secundaria', models.CharField(default='#f8fafc', max_length=7)),
                ('competicoes', models.ManyToManyField(blank=True, related_name='clubes', to='clubs.competition')),
                ('liga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubes', to='clubs.league')),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes',
                'ordering': ['-prestigio', 'nome'],
            },
        ),
    ]
