# Generated by Django 5.0.6 on 2026-08-25 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0001_initial'),
        ('clubs', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversario', models.CharField(max_length=120)),
                ('importancia', models.CharField(choices=[('normal', 'Normal'), ('decisiva', 'Decisiva'), ('final', 'Final'), ('classico', 'Clássico')], default='normal', max_length=10)),
                ('forca_adversario', models.PositiveSmallIntegerField(default=60)),
                ('mandante', models.BooleanField(default=True)),
                ('gols_time', models.PositiveSmallIntegerField(default=0)),
                ('gols_adversario', models.PositiveSmallIntegerField(default=0)),
                ('gols_jogador', models.PositiveSmallIntegerField(default=0)),
                ('assistencias_jogador', models.PositiveSmallIntegerField(default=0)),
                ('nota_jogador', models.DecimalField(decimal_places=1, default=6.0, max_digits=3)),
                ('titular', models.BooleanField(default=True)),
                ('minutos_jogados', models.PositiveSmallIntegerField(default=90)),
                ('simulada_em', models.DateTimeField(auto_now_add=True)),
                ('competicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.competition')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='players.player')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='career.season')),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['-simulada_em'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('gol', 'Gol'), ('assistencia', 'Assistência'), ('chance', 'Chance de Gol'), ('decisao', 'Decisão do Jogador'), ('cartao', 'Cartão'), ('lesao', 'Lesão'), ('substituicao', 'Substituição'), ('narracao', 'Narração')], max_length=20)),
                ('descricao', models.CharField(max_length=255)),
                ('escolha_disponivel', models.JSONField(blank=True, help_text='Lista de opções apresentadas ao jogador nesse minuto, se houver.', null=True)),
                ('escolha_feita', models.CharField(blank=True, max_length=50)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='matches.match')),
            ],
            options={
                'verbose_name': 'Evento de Partida',
                'verbose_name_plural': 'Eventos de Partida',
                'ordering': ['minuto'],
            },
        ),
    ]
